M48
; DRILL file {KiCad (6.0.1)} date Wed Nov 23 23:22:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-23T23:22:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X53.2Y-140.1
T1
G00X53.2Y-145.975
M15
G01X53.2Y-146.225
M16
G05
T0
M30
